{  
   "players":[  
      {  
         "type":"player",
         "playerId":93144,
         "playerFirstName":"Salvador",
         "playerLastName":"Perez",
         "city":"Valencia",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Salvador Perez started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Salvador Perez was born in Valencia, Venezuela on 1990\/05\/10 and is 25 years old, with a height of 6-3 and weighing in at 240lbs."
      },
      {  
         "type":"player",
         "playerId":94908,
         "playerFirstName":"Scott",
         "playerLastName":"Alexander",
         "city":"Santa Rosa",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Scott Alexander started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Scott Alexander was born in Santa Rosa, CA on 1989\/07\/10 and is 26 years old, with a height of 6-2 and weighing in at 190lbs."
      },
      {  
         "type":"player",
         "playerId":94909,
         "playerFirstName":"Miguel",
         "playerLastName":"Almonte",
         "city":"Santiago",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Miguel Almonte started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Miguel Almonte was born in Santiago, Dom. Rep. on 1993\/04\/04 and is 23 years old, with a height of 6-2 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":94910,
         "playerFirstName":"Clint",
         "playerLastName":"Barmes",
         "city":"Vincennes",
         "area":"IN",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Clint Barmes started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Clint Barmes was born in Vincennes, IN on 1979\/03\/06 and is 37 years old, with a height of 6-1 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94911,
         "playerFirstName":"Brian",
         "playerLastName":"Bocock",
         "city":"Harrisonburg",
         "area":"VA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brian Bocock started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brian Bocock was born in Harrisonburg, VA on 1985\/03\/09 and is 31 years old, with a height of 5-11 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94912,
         "playerFirstName":"Jorge",
         "playerLastName":"Bonifacio",
         "city":"Santo Domingo",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Jorge Bonifacio started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Jorge Bonifacio was born in Santo Domingo, Dom. Rep. on 1993\/06\/04 and is 22 years old, with a height of 6-1 and weighing in at 195lbs."
      },
      {  
         "type":"player",
         "playerId":94913,
         "playerFirstName":"Drew",
         "playerLastName":"Butera",
         "city":"Evansville",
         "area":"IL",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Drew Butera started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Drew Butera was born in Evansville, IL on 1983\/08\/09 and is 32 years old, with a height of 6-1 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94914,
         "playerFirstName":"Lorenzo",
         "playerLastName":"Cain",
         "city":"Valdosta",
         "area":"GA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Lorenzo Cain started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Lorenzo Cain was born in Valdosta, GA on 1986\/04\/13 and is 30 years old, with a height of 6-2 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94915,
         "playerFirstName":"Orlando",
         "playerLastName":"Calixte",
         "city":"Santo Domingo",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Orlando Calixte started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Orlando Calixte was born in Santo Domingo, Dom. Rep. on 1992\/02\/03 and is 24 years old, with a height of 5-11 and weighing in at 160lbs."
      },
      {  
         "type":"player",
         "playerId":94916,
         "playerFirstName":"Johermyn",
         "playerLastName":"Chavez",
         "city":"Turmero",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Johermyn Chavez started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Johermyn Chavez was born in Turmero, Venezuela on 1989\/01\/26 and is 27 years old, with a height of 6-3 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94917,
         "playerFirstName":"Cody",
         "playerLastName":"Clark",
         "city":"FAYETTEVILLE",
         "area":"AR",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Cody Clark started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Cody Clark was born in FAYETTEVILLE, AR on 1981\/09\/14 and is 34 years old, with a height of 6-3 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94918,
         "playerFirstName":"Dusty",
         "playerLastName":"Coleman",
         "city":"Sioux Falls",
         "area":"SD",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Dusty Coleman started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Dusty Coleman was born in Sioux Falls, SD on 1987\/04\/20 and is 29 years old, with a height of 6-2 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94919,
         "playerFirstName":"Tim",
         "playerLastName":"Collins",
         "city":"Worcester",
         "area":"MA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Tim Collins started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Tim Collins was born in Worcester, MA on 1989\/08\/21 and is 26 years old, with a height of 5-7 and weighing in at 170lbs."
      },
      {  
         "type":"player",
         "playerId":94920,
         "playerFirstName":"Christian",
         "playerLastName":"Colon",
         "city":"Cayey",
         "area":"PR",
         "country":"PUR",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Christian Colon started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Christian Colon was born in Cayey, PR on 1989\/05\/14 and is 26 years old, with a height of 5-10 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94921,
         "playerFirstName":"Antonio",
         "playerLastName":"Cruz",
         "city":"Santo Domingo",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Antonio Cruz started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Antonio Cruz was born in Santo Domingo, Dom. Rep. on 1991\/10\/07 and is 24 years old, with a height of 5-11 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94922,
         "playerFirstName":"Tony",
         "playerLastName":"Cruz",
         "city":"Palm Beach",
         "area":"FL",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Tony Cruz started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Tony Cruz was born in Palm Beach, FL on 1986\/08\/18 and is 29 years old, with a height of 5-11 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":94923,
         "playerFirstName":"Cheslor",
         "playerLastName":"Cuthbert",
         "city":"Corn Island",
         "area":"Nicaragua",
         "country":"NCA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Cheslor Cuthbert started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Cheslor Cuthbert was born in Corn Island, Nicaragua on 1992\/11\/16 and is 23 years old, with a height of 6-1 and weighing in at 190lbs."
      },
      {  
         "type":"player",
         "playerId":94924,
         "playerFirstName":"Wade",
         "playerLastName":"Davis",
         "city":"Lake Wales",
         "area":"FL",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Wade Davis started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Wade Davis was born in Lake Wales, FL on 1985\/09\/07 and is 30 years old, with a height of 6-5 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94925,
         "playerFirstName":"Cody",
         "playerLastName":"Decker",
         "city":"Santa Monica",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Cody Decker started his MLB career on [MONTH] [DAY], [YEAR] for the Colorado Rockies, accumulating [##] years in the MLB. Cody Decker was born in Santa Monica, CA on 1987\/01\/17 and is 29 years old, with a height of 5-11 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94926,
         "playerFirstName":"Hunter",
         "playerLastName":"Dozier",
         "city":"Denton",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Hunter Dozier started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Hunter Dozier was born in Denton, TX on 1991\/08\/22 and is 24 years old, with a height of 6-4 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94927,
         "playerFirstName":"Brian",
         "playerLastName":"Duensing",
         "city":"Marysville",
         "area":"KS",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brian Duensing started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brian Duensing was born in Marysville, KS on 1983\/02\/22 and is 33 years old, with a height of 6-0 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94928,
         "playerFirstName":"Danny",
         "playerLastName":"Duffy",
         "city":"Goleta",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Danny Duffy started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Danny Duffy was born in Goleta, CA on 1988\/12\/21 and is 27 years old, with a height of 6-3 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94929,
         "playerFirstName":"Jarrod",
         "playerLastName":"Dyson",
         "city":"McComb",
         "area":"MS",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Jarrod Dyson started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Jarrod Dyson was born in McComb, MS on 1984\/08\/15 and is 31 years old, with a height of 5-10 and weighing in at 165lbs."
      },
      {  
         "type":"player",
         "playerId":94930,
         "playerFirstName":"Brett",
         "playerLastName":"Eibner",
         "city":"The Woodlands",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brett Eibner started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brett Eibner was born in The Woodlands, TX on 1988\/12\/02 and is 27 years old, with a height of 6-4 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94931,
         "playerFirstName":"Alcides",
         "playerLastName":"Escobar",
         "city":"La Sabana",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Alcides Escobar started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Alcides Escobar was born in La Sabana, Venezuela on 1986\/12\/16 and is 29 years old, with a height of 6-1 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94932,
         "playerFirstName":"Brian",
         "playerLastName":"Flynn",
         "city":"Tulsa",
         "area":"OK",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brian Flynn started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brian Flynn was born in Tulsa, OK on 1990\/04\/19 and is 26 years old, with a height of 6-7 and weighing in at 250lbs."
      },
      {  
         "type":"player",
         "playerId":94933,
         "playerFirstName":"Reymond",
         "playerLastName":"Fuentes",
         "city":"Orlando",
         "area":"FL",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Reymond Fuentes started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Reymond Fuentes was born in Orlando, FL on 1991\/02\/12 and is 25 years old, with a height of 6-0 and weighing in at 160lbs."
      },
      {  
         "type":"player",
         "playerId":94934,
         "playerFirstName":"Dillon",
         "playerLastName":"Gee",
         "city":"Cleburne",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Dillon Gee started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Dillon Gee was born in Cleburne, TX on 1986\/04\/28 and is 30 years old, with a height of 6-1 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94935,
         "playerFirstName":"Alex",
         "playerLastName":"Gordon",
         "city":"Lincoln",
         "area":"NE",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Alex Gordon started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Alex Gordon was born in Lincoln, NE on 1984\/02\/10 and is 32 years old, with a height of 6-1 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94936,
         "playerFirstName":"Terrance",
         "playerLastName":"Gore",
         "city":"Macon",
         "area":"GA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Terrance Gore started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Terrance Gore was born in Macon, GA on 1991\/06\/08 and is 24 years old, with a height of 5-7 and weighing in at 165lbs."
      },
      {  
         "type":"player",
         "playerId":94937,
         "playerFirstName":"Kelvin",
         "playerLastName":"Herrera",
         "city":"Tenares",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Kelvin Herrera started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Kelvin Herrera was born in Tenares, Dom. Rep. on 1989\/12\/31 and is 26 years old, with a height of 5-10 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94938,
         "playerFirstName":"Luke",
         "playerLastName":"Hochevar",
         "city":"Denver",
         "area":"CO",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Luke Hochevar started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Luke Hochevar was born in Denver, CO on 1983\/09\/15 and is 32 years old, with a height of 6-5 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94939,
         "playerFirstName":"Eric",
         "playerLastName":"Hosmer",
         "city":"South Miami",
         "area":"FL",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Eric Hosmer started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Eric Hosmer was born in South Miami, FL on 1989\/10\/24 and is 26 years old, with a height of 6-4 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94940,
         "playerFirstName":"David",
         "playerLastName":"Huff",
         "city":"San Diego",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"David Huff started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. David Huff was born in San Diego, CA on 1984\/08\/22 and is 31 years old, with a height of 6-1 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":94941,
         "playerFirstName":"Omar",
         "playerLastName":"Infante",
         "city":"Puerto La Cruz",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Omar Infante started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Omar Infante was born in Puerto La Cruz, Venezuela on 1981\/12\/26 and is 34 years old, with a height of 5-11 and weighing in at 195lbs."
      },
      {  
         "type":"player",
         "playerId":94942,
         "playerFirstName":"Brandon",
         "playerLastName":"Jacobs",
         "city":"Snellville",
         "area":"GA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brandon Jacobs started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brandon Jacobs was born in Snellville, GA on 1990\/12\/08 and is 25 years old, with a height of 6-1 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94943,
         "playerFirstName":"Ian",
         "playerLastName":"Kennedy",
         "city":"Huntington Beach",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Ian Kennedy started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Ian Kennedy was born in Huntington Beach, CA on 1984\/12\/19 and is 31 years old, with a height of 6-0 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94944,
         "playerFirstName":"John",
         "playerLastName":"Lannan",
         "city":"Long Beach",
         "area":"NY",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"John Lannan started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. John Lannan was born in Long Beach, NY on 1984\/09\/27 and is 31 years old, with a height of 6-4 and weighing in at 235lbs."
      },
      {  
         "type":"player",
         "playerId":94945,
         "playerFirstName":"Jose A.",
         "playerLastName":"Martinez",
         "city":"La Guaira",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Jose A. Martinez started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Jose A. Martinez was born in La Guaira, Venezuela on 1988\/07\/25 and is 27 years old, with a height of 6-6 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":94946,
         "playerFirstName":"Kris",
         "playerLastName":"Medlen",
         "city":"Artesia",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Kris Medlen started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Kris Medlen was born in Artesia, CA on 1985\/10\/07 and is 30 years old, with a height of 5-10 and weighing in at 190lbs."
      },
      {  
         "type":"player",
         "playerId":94947,
         "playerFirstName":"Whit",
         "playerLastName":"Merrifield",
         "city":"Advance",
         "area":"NC",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Whit Merrifield started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Whit Merrifield was born in Advance, NC on 1989\/01\/24 and is 27 years old, with a height of 6-1 and weighing in at 175lbs."
      },
      {  
         "type":"player",
         "playerId":94948,
         "playerFirstName":"Alec",
         "playerLastName":"Mills",
         "city":"Clarksville",
         "area":"TN",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Alec Mills started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Alec Mills was born in Clarksville, TN on 1991\/11\/30 and is 24 years old, with a height of 6-4 and weighing in at 190lbs."
      },
      {  
         "type":"player",
         "playerId":94949,
         "playerFirstName":"Mike",
         "playerLastName":"Minor",
         "city":"Chapel Hill",
         "area":"TN",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Mike Minor started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Mike Minor was born in Chapel Hill, TN on 1987\/12\/26 and is 28 years old, with a height of 6-4 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":94950,
         "playerFirstName":"Raul",
         "playerLastName":"Mondesi Jr.",
         "city":"Los Angeles",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Raul Mondesi Jr. started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Raul Mondesi Jr. was born in Los Angeles, CA on 1995\/07\/27 and is 20 years old, with a height of 6-1 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94951,
         "playerFirstName":"Kendrys",
         "playerLastName":"Morales",
         "city":"Fomento",
         "area":"Cuba",
         "country":"CUB",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Kendrys Morales started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Kendrys Morales was born in Fomento, Cuba on 1983\/06\/20 and is 32 years old, with a height of 6-1 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94952,
         "playerFirstName":"Clayton",
         "playerLastName":"Mortensen",
         "city":"Rexburg",
         "area":"ID",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Clayton Mortensen started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Clayton Mortensen was born in Rexburg, ID on 1985\/04\/10 and is 31 years old, with a height of 6-4 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94953,
         "playerFirstName":"Mike",
         "playerLastName":"Moustakas",
         "city":"Los Angeles",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Mike Moustakas started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Mike Moustakas was born in Los Angeles, CA on 1988\/09\/11 and is 27 years old, with a height of 6-0 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":94954,
         "playerFirstName":"Peter",
         "playerLastName":"Moylan",
         "city":"Lesmurdie",
         "area":"Australia",
         "country":"AUS",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Peter Moylan started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Peter Moylan was born in Lesmurdie, Australia on 1978\/12\/02 and is 37 years old, with a height of 6-2 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94956,
         "playerFirstName":"Lester",
         "playerLastName":"Oliveros",
         "city":"Maracay",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Lester Oliveros started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Lester Oliveros was born in Maracay, Venezuela on 1988\/05\/28 and is 27 years old, with a height of 6-0 and weighing in at 235lbs."
      },
      {  
         "type":"player",
         "playerId":94957,
         "playerFirstName":"Paulo",
         "playerLastName":"Orlando",
         "city":"Sao Paulo",
         "area":"Brazil",
         "country":"BRA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Paulo Orlando started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Paulo Orlando was born in Sao Paulo, Brazil on 1985\/11\/01 and is 30 years old, with a height of 6-2 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":94958,
         "playerFirstName":"Brooks",
         "playerLastName":"Pounders",
         "city":"Temecula",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Brooks Pounders started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Brooks Pounders was born in Temecula, CA on 1990\/09\/26 and is 25 years old, with a height of 6-4 and weighing in at 270lbs."
      },
      {  
         "type":"player",
         "playerId":94959,
         "playerFirstName":"Max",
         "playerLastName":"Ramirez",
         "city":"Barquisimeto",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Max Ramirez started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Max Ramirez was born in Barquisimeto, Venezuela on 1984\/10\/11 and is 31 years old, with a height of 5-11 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94960,
         "playerFirstName":"Reid",
         "playerLastName":"Redman",
         "city":"Lubbock",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Reid Redman started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Reid Redman was born in Lubbock, TX on 1988\/11\/22 and is 27 years old, with a height of 6-0 and weighing in at 180lbs."
      },
      {  
         "type":"player",
         "playerId":94961,
         "playerFirstName":"Sam",
         "playerLastName":"Selman",
         "city":"Austin",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Sam Selman started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Sam Selman was born in Austin, TX on 1990\/11\/14 and is 25 years old, with a height of 6-3 and weighing in at 195lbs."
      },
      {  
         "type":"player",
         "playerId":94962,
         "playerFirstName":"Travis",
         "playerLastName":"Snider",
         "city":"Kirkland",
         "area":"WA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Travis Snider started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Travis Snider was born in Kirkland, WA on 1988\/02\/02 and is 28 years old, with a height of 6-0 and weighing in at 235lbs."
      },
      {  
         "type":"player",
         "playerId":94963,
         "playerFirstName":"Joakim",
         "playerLastName":"Soria",
         "city":"Monclova",
         "area":"Mexico",
         "country":"MEX",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Joakim Soria started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Joakim Soria was born in Monclova, Mexico on 1984\/05\/18 and is 31 years old, with a height of 6-3 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94964,
         "playerFirstName":"Bubba",
         "playerLastName":"Starling",
         "city":"Gardner",
         "area":"KS",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Bubba Starling started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Bubba Starling was born in Gardner, KS on 1992\/08\/03 and is 23 years old, with a height of 6-4 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":94965,
         "playerFirstName":"Matt",
         "playerLastName":"Strahm",
         "city":"West Fargo",
         "area":"ND",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Matt Strahm started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Matt Strahm was born in West Fargo, ND on 1991\/11\/12 and is 24 years old, with a height of 6-3 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":94966,
         "playerFirstName":"Ramon",
         "playerLastName":"Torres",
         "city":"Moncion",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Ramon Torres started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Ramon Torres was born in Moncion, Dom. Rep. on 1993\/01\/22 and is 23 years old, with a height of 5-11 and weighing in at 170lbs."
      },
      {  
         "type":"player",
         "playerId":94967,
         "playerFirstName":"Jason",
         "playerLastName":"Vargas",
         "city":"Apple Valley",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Jason Vargas started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Jason Vargas was born in Apple Valley, CA on 1983\/02\/02 and is 33 years old, with a height of 6-0 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":94968,
         "playerFirstName":"Yordano",
         "playerLastName":"Ventura",
         "city":"Samana",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Yordano Ventura started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Yordano Ventura was born in Samana, Dom. Rep. on 1991\/06\/03 and is 24 years old, with a height of 6-0 and weighing in at 195lbs."
      },
      {  
         "type":"player",
         "playerId":94969,
         "playerFirstName":"Edinson",
         "playerLastName":"Volquez",
         "city":"Barahona",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Edinson Volquez started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Edinson Volquez was born in Barahona, Dom. Rep. on 1983\/07\/03 and is 32 years old, with a height of 6-0 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94970,
         "playerFirstName":"Chien-Ming",
         "playerLastName":"Wang",
         "city":"Tainan",
         "area":"Taiwan",
         "country":"TWN",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Chien-Ming Wang started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Chien-Ming Wang was born in Tainan, Taiwan on 1980\/03\/31 and is 36 years old, with a height of 6-4 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94971,
         "playerFirstName":"Chris",
         "playerLastName":"Young",
         "city":"Dallas",
         "area":"TX",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Chris Young started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Chris Young was born in Dallas, TX on 1979\/05\/25 and is 36 years old, with a height of 6-10 and weighing in at 255lbs."
      },
      {  
         "type":"player",
         "playerId":94972,
         "playerFirstName":"Kyle",
         "playerLastName":"Zimmer",
         "city":"San Francisco",
         "area":"CA",
         "country":"USA",
         "teamName":"Kansas City Royals",
         "teamId":2806,
         "playerDescription":"Kyle Zimmer started his MLB career on [MONTH] [DAY], [YEAR] for the Kansas City Royals, accumulating [##] years in the MLB. Kyle Zimmer was born in San Francisco, CA on 1991\/09\/13 and is 24 years old, with a height of 6-3 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94900,
         "playerFirstName":"Jose A.",
         "playerLastName":"Valdez",
         "city":"Don Gregorio de Nizao",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Jose A. Valdez started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Jose A. Valdez was born in Don Gregorio de Nizao, Dom. Rep. on 1990\/03\/01 and is 26 years old, with a height of 6-1 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":94901,
         "playerFirstName":"Drew",
         "playerLastName":"VerHagen",
         "city":"Royse City",
         "area":"TX",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Drew VerHagen started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Drew VerHagen was born in Royse City, TX on 1990\/10\/22 and is 25 years old, with a height of 6-6 and weighing in at 230lbs."
      },
      {  
         "type":"player",
         "playerId":94902,
         "playerFirstName":"Justin",
         "playerLastName":"Verlander",
         "city":"Manakin-Sabot",
         "area":"VA",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Justin Verlander started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Justin Verlander was born in Manakin-Sabot, VA on 1983\/02\/20 and is 33 years old, with a height of 6-5 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94903,
         "playerFirstName":"Thad",
         "playerLastName":"Weber",
         "city":"Seward",
         "area":"NE",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Thad Weber started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Thad Weber was born in Seward, NE on 1984\/09\/28 and is 31 years old, with a height of 6-2 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94904,
         "playerFirstName":"Casper",
         "playerLastName":"Wells",
         "city":"Grand Rapids",
         "area":"MI",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Casper Wells started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Casper Wells was born in Grand Rapids, MI on 1984\/11\/23 and is 31 years old, with a height of 6-2 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":94905,
         "playerFirstName":"Alex",
         "playerLastName":"Wilson",
         "city":"Dhahran",
         "area":"Saudi Arabi",
         "country":"KSA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Alex Wilson started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Alex Wilson was born in Dhahran, Saudi Arabi on 1986\/11\/03 and is 29 years old, with a height of 6-0 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":94906,
         "playerFirstName":"Justin",
         "playerLastName":"Wilson",
         "city":"Anaheim",
         "area":"CA",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Justin Wilson started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Justin Wilson was born in Anaheim, CA on 1987\/08\/18 and is 28 years old, with a height of 6-2 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":94907,
         "playerFirstName":"Jordan",
         "playerLastName":"Zimmermann",
         "city":"Auburndale",
         "area":"WI",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Jordan Zimmermann started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Jordan Zimmermann was born in Auburndale, WI on 1986\/05\/23 and is 29 years old, with a height of 6-2 and weighing in at 225lbs."
      },
      {  
         "type":"player",
         "playerId":94990,
         "playerFirstName":"John",
         "playerLastName":"Hicks",
         "city":"Richmond",
         "area":"VA",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"John Hicks started his MLB career on [MONTH] [DAY], [YEAR] for the Minnesota Twins, accumulating [##] years in the MLB. John Hicks was born in Richmond, VA on 1989\/08\/31 and is 26 years old, with a height of 6-2 and weighing in at 230lbs."
      },
      {  
         "type":"player",
         "playerId":95362,
         "playerFirstName":"Humberto",
         "playerLastName":"Quintero",
         "city":"Maracaibo",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Humberto Quintero started his MLB career on [MONTH] [DAY], [YEAR] for the Toronto Blue Jays, accumulating [##] years in the MLB. Humberto Quintero was born in Maracaibo, Venezuela on 1979\/08\/02 and is 36 years old, with a height of 5-10 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":95667,
         "playerFirstName":"Myles",
         "playerLastName":"Jaye",
         "city":"Fayetteville",
         "area":"GA",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Myles Jaye started his MLB career on [MONTH] [DAY], [YEAR] for the Texas Rangers, accumulating [##] years in the MLB. Myles Jaye was born in Fayetteville, GA on 1991\/12\/28 and is 24 years old, with a height of 6-3 and weighing in at 170lbs."
      },
      {  
         "type":"player",
         "playerId":95701,
         "playerFirstName":"Bobby",
         "playerLastName":"Wilson",
         "city":"Dunedin",
         "area":"FL",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Bobby Wilson started his MLB career on [MONTH] [DAY], [YEAR] for the Texas Rangers, accumulating [##] years in the MLB. Bobby Wilson was born in Dunedin, FL on 1983\/04\/08 and is 33 years old, with a height of 6-0 and weighing in at 230lbs."
      },
      {  
         "type":"player",
         "playerId":96157,
         "playerFirstName":"Yordy",
         "playerLastName":"Cabrera",
         "city":"Lakeland",
         "area":"FL",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Yordy Cabrera started his MLB career on [MONTH] [DAY], [YEAR] for the Miami Marlins, accumulating [##] years in the MLB. Yordy Cabrera was born in Lakeland, FL on 1990\/09\/03 and is 25 years old, with a height of 6-1 and weighing in at 205lbs."
      },
      {  
         "type":"player",
         "playerId":100954,
         "playerFirstName":"Chad",
         "playerLastName":"Bell",
         "city":"Knoxville",
         "area":"TN",
         "country":"USA",
         "teamName":"Detroit Tigers",
         "teamId":2797,
         "playerDescription":"Chad Bell started his MLB career on [MONTH] [DAY], [YEAR] for the Detroit Tigers, accumulating [##] years in the MLB. Chad Bell was born in Knoxville, TN on 1989\/02\/28 and is 27 years old, with a height of 6-3 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":96763,
         "playerFirstName":"Seth",
         "playerLastName":"Streich",
         "city":"Johnsonburg",
         "area":"PA",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Seth Streich started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Seth Streich was born in Johnsonburg, PA on 1991\/02\/19 and is 25 years old, with a height of 6-3 and weighing in at 210lbs."
      },
      {  
         "type":"player",
         "playerId":96764,
         "playerFirstName":"Jose",
         "playerLastName":"Torres",
         "city":"Caracas",
         "area":"Venezuela",
         "country":"VEN",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Jose Torres started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Jose Torres was born in Caracas, Venezuela on 1993\/09\/24 and is 22 years old, with a height of 6-2 and weighing in at 175lbs."
      },
      {  
         "type":"player",
         "playerId":96765,
         "playerFirstName":"Melvin",
         "playerLastName":"Upton Jr.",
         "city":"Norfolk",
         "area":"VA",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Melvin Upton Jr. started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Melvin Upton Jr. was born in Norfolk, VA on 1984\/08\/21 and is 31 years old, with a height of 6-3 and weighing in at 185lbs."
      },
      {  
         "type":"player",
         "playerId":96766,
         "playerFirstName":"Cesar",
         "playerLastName":"Vargas",
         "city":"Puebla",
         "area":"Mexico",
         "country":"MEX",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Cesar Vargas started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Cesar Vargas was born in Puebla, Mexico on 1991\/12\/30 and is 24 years old, with a height of 6-1 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":96767,
         "playerFirstName":"Carlos",
         "playerLastName":"Villanueva",
         "city":"Santiago",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Carlos Villanueva started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Carlos Villanueva was born in Santiago, Dom. Rep. on 1983\/11\/28 and is 32 years old, with a height of 6-2 and weighing in at 215lbs."
      },
      {  
         "type":"player",
         "playerId":96769,
         "playerFirstName":"Brett",
         "playerLastName":"Wallace",
         "city":"Marin",
         "area":"CA",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Brett Wallace started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Brett Wallace was born in Marin, CA on 1986\/08\/26 and is 29 years old, with a height of 6-2 and weighing in at 235lbs."
      },
      {  
         "type":"player",
         "playerId":96770,
         "playerFirstName":"Nelson",
         "playerLastName":"Ward",
         "city":"Marietta",
         "area":"GA",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Nelson Ward started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Nelson Ward was born in Marietta, GA on 1992\/08\/06 and is 23 years old, with a height of 5-11 and weighing in at 175lbs."
      },
      {  
         "type":"player",
         "playerId":96771,
         "playerFirstName":"Jemile",
         "playerLastName":"Weeks",
         "city":"Orlando",
         "area":"FL",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Jemile Weeks started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Jemile Weeks was born in Orlando, FL on 1987\/01\/26 and is 29 years old, with a height of 5-9 and weighing in at 170lbs."
      },
      {  
         "type":"player",
         "playerId":96853,
         "playerFirstName":"Justin",
         "playerLastName":"Sellers",
         "city":"Bellflower",
         "area":"CA",
         "country":"USA",
         "teamName":"San Diego Padres",
         "teamId":2794,
         "playerDescription":"Justin Sellers started his MLB career on [MONTH] [DAY], [YEAR] for the San Diego Padres, accumulating [##] years in the MLB. Justin Sellers was born in Bellflower, CA on 1986\/02\/01 and is 30 years old, with a height of 5-10 and weighing in at 175lbs."
      },
      {  
         "type":"player",
         "playerId":96932,
         "playerFirstName":"Jose",
         "playerLastName":"De Paula",
         "city":"Villa Mella",
         "area":"Dom. Rep.",
         "country":"DOM",
         "teamName":"Los Angeles Dodgers",
         "teamId":2818,
         "playerDescription":"Jose De Paula started his MLB career on [MONTH] [DAY], [YEAR] for the Los Angeles Dodgers, accumulating [##] years in the MLB. Jose De Paula was born in Villa Mella, Dom. Rep. on 1988\/03\/04 and is 28 years old, with a height of 6-1 and weighing in at 170lbs."
      },
      {  
         "type":"player",
         "playerId":96142,
         "playerFirstName":"Chris",
         "playerLastName":"Withrow",
         "city":"Midland",
         "area":"TX",
         "country":"USA",
         "teamName":"Atlanta Braves",
         "teamId":2796,
         "playerDescription":"Chris Withrow started his MLB career on [MONTH] [DAY], [YEAR] for the Atlanta Braves, accumulating [##] years in the MLB. Chris Withrow was born in Midland, TX on 1989\/04\/01 and is 27 years old, with a height of 6-3 and weighing in at 240lbs."
      },
      {  
         "type":"player",
         "playerId":96143,
         "playerFirstName":"Rob",
         "playerLastName":"Wooten",
         "city":"Goldsboro",
         "area":"NC",
         "country":"USA",
         "teamName":"Atlanta Braves",
         "teamId":2796,
         "playerDescription":"Rob Wooten started his MLB career on [MONTH] [DAY], [YEAR] for the Atlanta Braves, accumulating [##] years in the MLB. Rob Wooten was born in Goldsboro, NC on 1985\/07\/21 and is 30 years old, with a height of 6-1 and weighing in at 200lbs."
      },
      {  
         "type":"player",
         "playerId":96381,
         "playerFirstName":"Sean",
         "playerLastName":"Burnett",
         "city":"Dunedin",
         "area":"FL",
         "country":"USA",
         "teamName":"Atlanta Braves",
         "teamId":2796,
         "playerDescription":"Sean Burnett started his MLB career on [MONTH] [DAY], [YEAR] for the Atlanta Braves, accumulating [##] years in the MLB. Sean Burnett was born in Dunedin, FL on 1982\/09\/17 and is 33 years old, with a height of 6-1 and weighing in at 180lbs."
      },
      {  
         "type":"player",
         "playerId":96421,
         "playerFirstName":"Tyler",
         "playerLastName":"Moore",
         "city":"Brandon",
         "area":"MS",
         "country":"USA",
         "teamName":"Atlanta Braves",
         "teamId":2796,
         "playerDescription":"Tyler Moore started his MLB career on [MONTH] [DAY], [YEAR] for the Atlanta Braves, accumulating [##] years in the MLB. Tyler Moore was born in Brandon, MS on 1987\/01\/30 and is 29 years old, with a height of 6-2 and weighing in at 220lbs."
      },
      {  
         "type":"player",
         "playerId":96888,
         "playerFirstName":"Phil",
         "playerLastName":"Coke",
         "city":"Sonora",
         "area":"CA",
         "country":"USA",
         "teamName":"Atlanta Braves",
         "teamId":2796,
         "playerDescription":"Phil Coke started his MLB career on [MONTH] [DAY], [YEAR] for the Atlanta Braves, accumulating [##] years in the MLB. Phil Coke was born in Sonora, CA on 1982\/07\/19 and is 33 years old, with a height of 6-1 and weighing in at 210lbs."
      }
   ],
   "teams":[  
      {  
         "type":"team",
         "teamId":2799,
         "teamFirstName":"Baltimore",
         "teamLastName":"Orioles",
         "teamCity":"Baltimore",
         "teamState":"Maryland",
         "teamCountry":"USA",
         "teamVenue":"Oriole Park at Camden Yards",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Baltimore_Orioles_Logo.jpg",
         "teamDescription":"The Baltimore Orioles (18-12) is in the American East division and are currently on a 2 win streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2810,
         "teamFirstName":"Minnesota",
         "teamLastName":"Twins",
         "teamCity":"Minneapolis",
         "teamState":"Minnesota",
         "teamCountry":"USA",
         "teamVenue":"Target Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Minnesota_Twins_Logo.jpg",
         "teamDescription":"The Minnesota Twins (8-23) is in the American Central division and are currently on a 5 loss streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2792,
         "teamFirstName":"Los Angeles",
         "teamLastName":"Angels",
         "teamCity":"Anaheim",
         "teamState":"California",
         "teamCountry":"USA",
         "teamVenue":"Angel Stadium of Anaheim",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Los_Angeles_Angels_Logo.jpg",
         "teamDescription":"The Los Angeles Angels (13-18) is in the American West division and are currently on a 3 loss streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2808,
         "teamFirstName":"Oakland",
         "teamLastName":"Athletics",
         "teamCity":"Oakland",
         "teamState":"California",
         "teamCountry":"USA",
         "teamVenue":"Oakland Coliseum",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Oakland-_Athletics_Logo.jpg",
         "teamDescription":"The Oakland Athletics (14-18) is in the American West division and are currently on a 2 loss streak with a ranking of 3."
      },
      {  
         "type":"team",
         "teamId":2804,
         "teamFirstName":"Seattle",
         "teamLastName":"Mariners",
         "teamCity":"Seattle",
         "teamState":"Washington",
         "teamCountry":"USA",
         "teamVenue":"Safeco Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Seattle_Mariners_Logo.jpg",
         "teamDescription":"The Seattle Mariners (18-13) is in the American West division and are currently on a 1 loss streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2807,
         "teamFirstName":"Texas",
         "teamLastName":"Rangers",
         "teamCity":"Arlington",
         "teamState":"Texas",
         "teamCountry":"USA",
         "teamVenue":"Globe Life Park in Arlington",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Texas_Rangers_Logo.jpg",
         "teamDescription":"The Texas Rangers (18-14) is in the American West division and are currently on a 3 win streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2796,
         "teamFirstName":"Atlanta",
         "teamLastName":"Braves",
         "teamCity":"Atlanta",
         "teamState":"Georgia",
         "teamCountry":"USA",
         "teamVenue":"Turner Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Atlanta_Braves_Logo.jpg",
         "teamDescription":"The Atlanta Braves (7-23) is in the National East division and are currently on a 4 loss streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2814,
         "teamFirstName":"Miami",
         "teamLastName":"Marlins",
         "teamCity":"Miami",
         "teamState":"Florida",
         "teamCountry":"USA",
         "teamVenue":"Marlins Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Miami_Marlins_Logo.jpg",
         "teamDescription":"The Miami Marlins (16-14) is in the National East division and are currently on a 2 loss streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2813,
         "teamFirstName":"Washington",
         "teamLastName":"Nationals",
         "teamCity":"Washington",
         "teamState":"D.C.",
         "teamCountry":"USA",
         "teamVenue":"Nationals Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Washington_Nationals_Logo.jpg",
         "teamDescription":"The Washington Nationals (19-12) is in the National East division and are currently on a 4 loss streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2812,
         "teamFirstName":"New York",
         "teamLastName":"Mets",
         "teamCity":"Queens",
         "teamState":"New York",
         "teamCountry":"USA",
         "teamVenue":"Citi Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_New_York_Mets_Logo.jpg",
         "teamDescription":"The New York Mets (19-11) is in the National East division and are currently on a 2 win streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2815,
         "teamFirstName":"Philadelphia",
         "teamLastName":"Phillies",
         "teamCity":"Philadelphia",
         "teamState":"Pennsylvania",
         "teamCountry":"USA",
         "teamVenue":"Citizens Bank Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Philadelphia_Phillies_Logo.jpg",
         "teamDescription":"The Philadelphia Phillies (18-14) is in the National East division and are currently on a 2 win streak with a ranking of 3."
      },
      {  
         "type":"team",
         "teamId":2791,
         "teamFirstName":"Boston",
         "teamLastName":"Red Sox",
         "teamCity":"Boston",
         "teamState":"Massachuettes",
         "teamCountry":"USA",
         "teamVenue":"Fenway Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Boston_Red_Sox_Logo.jpg",
         "teamDescription":"The Boston Red Sox (18-13) is in the American East division and are currently on a 1 win streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2795,
         "teamFirstName":"Chicago",
         "teamLastName":"Cubs",
         "teamCity":"Chicago",
         "teamState":"Illinois",
         "teamCountry":"USA",
         "teamVenue":"Wrigley Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Chicago_Cubs_Logo.jpg",
         "teamDescription":"The Chicago Cubs (24-6) is in the National Central division and are currently on a 7 win streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2816,
         "teamFirstName":"Cincinnati",
         "teamLastName":"Reds",
         "teamCity":"Cincinnati",
         "teamState":"Ohio",
         "teamCountry":"USA",
         "teamVenue":"Great American Ball Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Cincinnati_Reds_Logo.jpg",
         "teamDescription":"The Cincinnati Reds (13-19) is in the National Central division and are currently on a 2 loss streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2811,
         "teamFirstName":"Houston",
         "teamLastName":"Astros",
         "teamCity":"Houston",
         "teamState":"Texas",
         "teamCountry":"USA",
         "teamVenue":"Minute Maid Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Houston_Astros_Logo.jpg",
         "teamDescription":"The Houston Astros (12-20) is in the American West division and are currently on a 1 win streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2801,
         "teamFirstName":"Milwaukee",
         "teamLastName":"Brewers",
         "teamCity":"Milwaukee",
         "teamState":"Wisconsin",
         "teamCountry":"USA",
         "teamVenue":"Miller Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Milwaukee_Brewers_Logo.jpg",
         "teamDescription":"The Milwaukee Brewers (13-18) is in the National Central division and are currently on a 2 win streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2817,
         "teamFirstName":"Pittsburgh",
         "teamLastName":"Pirates",
         "teamCity":"Pittsburgh",
         "teamState":"Pennsylvania",
         "teamCountry":"USA",
         "teamVenue":"PNC Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Pittsburgh_Pirates_Logo.jpg",
         "teamDescription":"The Pittsburgh Pirates (17-14) is in the National Central division and are currently on a 1 win streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2805,
         "teamFirstName":"St. Louis",
         "teamLastName":"Cardinals",
         "teamCity":"St. Louis",
         "teamState":"Missouri",
         "teamCountry":"USA",
         "teamVenue":"Busch Stadium",
         "teamLogo":"\/mlb\/logos\/team\/MLB_St_Louis_Cardinals_Logo.jpg",
         "teamDescription":"The St. Louis Cardinals (16-16) is in the National Central division and are currently on a 1 loss streak with a ranking of 3."
      },
      {  
         "type":"team",
         "teamId":2793,
         "teamFirstName":"Arizona",
         "teamLastName":"Diamondbacks",
         "teamCity":"Phoenix",
         "teamState":"Arizona",
         "teamCountry":"USA",
         "teamVenue":"Chase Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Arizona_Diamondbacks_Logo.jpg",
         "teamDescription":"The Arizona Diamondbacks (15-18) is in the National West division and are currently on a 3 win streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2800,
         "teamFirstName":"Colorado",
         "teamLastName":"Rockies",
         "teamCity":"Devner",
         "teamState":"Colorado",
         "teamCountry":"USA",
         "teamVenue":"Coors Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Colorado_Rockies_Logo.jpg",
         "teamDescription":"The Colorado Rockies (15-16) is in the National West division and are currently on a 1 win streak with a ranking of 3."
      },
      {  
         "type":"team",
         "teamId":2818,
         "teamFirstName":"Los Angeles",
         "teamLastName":"Dodgers",
         "teamCity":"Los Angeles",
         "teamState":"California",
         "teamCountry":"USA",
         "teamVenue":"Dodger Stadium",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Los_Angeles_Dodgers_Logo.jpg",
         "teamDescription":"The Los Angeles Dodgers (16-15) is in the National West division and are currently on a 2 win streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2794,
         "teamFirstName":"San Diego",
         "teamLastName":"Padres",
         "teamCity":"San Diego",
         "teamState":"California",
         "teamCountry":"USA",
         "teamVenue":"Petco Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_San_Diego_Padres_Logo.jpg",
         "teamDescription":"The San Diego Padres (13-19) is in the National West division and are currently on a 2 loss streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2803,
         "teamFirstName":"New York",
         "teamLastName":"Yankees",
         "teamCity":"Bronx",
         "teamState":"New York",
         "teamCountry":"USA",
         "teamVenue":"Yankee Stadium",
         "teamLogo":"\/mlb\/logos\/team\/MLB_New_York_Yankees_Logo.jpg",
         "teamDescription":"The New York Yankees (11-18) is in the American East division and are currently on a 1 loss streak with a ranking of 5."
      },
      {  
         "type":"team",
         "teamId":2819,
         "teamFirstName":"San Francisco",
         "teamLastName":"Giants",
         "teamCity":"San Francisco",
         "teamState":"California",
         "teamCountry":"USA",
         "teamVenue":"AT&T Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_San_Francisco_Giants_Logo.jpg",
         "teamDescription":"The San Francisco Giants (17-16) is in the National West division and are currently on a 1 loss streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2798,
         "teamFirstName":"Tampa Bay",
         "teamLastName":"Rays",
         "teamCity":"St. Petersburg",
         "teamState":"Florida",
         "teamCountry":"USA",
         "teamVenue":"Tropicana Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Tampa_Bay_Rays_Logo.jpg",
         "teamDescription":"The Tampa Bay Rays (15-14) is in the American East division and are currently on a 4 win streak with a ranking of 3."
      },
      {  
         "type":"team",
         "teamId":2802,
         "teamFirstName":"Toronto",
         "teamLastName":"Blue Jays",
         "teamCity":"Toronto",
         "teamState":"Ontario",
         "teamCountry":"CAN",
         "teamVenue":"Rogers Centre",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Toronto_Blue_Jays_Logo.jpg",
         "teamDescription":"The Toronto Blue Jays (16-17) is in the American East division and are currently on a 2 loss streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2790,
         "teamFirstName":"Chicago",
         "teamLastName":"White Sox",
         "teamCity":"Chicago",
         "teamState":"Illinois",
         "teamCountry":"USA",
         "teamVenue":"U.S. Cellular Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Chicago_White_Sox_Logo.jpg",
         "teamDescription":"The Chicago White Sox (22-10) is in the American Central division and are currently on a 3 win streak with a ranking of 1."
      },
      {  
         "type":"team",
         "teamId":2809,
         "teamFirstName":"Cleveland",
         "teamLastName":"Indians",
         "teamCity":"Cleveland",
         "teamState":"Ohio",
         "teamCountry":"USA",
         "teamVenue":"Progressive Field",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Cleveland_Indians_Logo.jpg",
         "teamDescription":"The Cleveland Indians (15-13) is in the American Central division and are currently on a 1 win streak with a ranking of 2."
      },
      {  
         "type":"team",
         "teamId":2797,
         "teamFirstName":"Detroit",
         "teamLastName":"Tigers",
         "teamCity":"Detroit",
         "teamState":"Michigan",
         "teamCountry":"USA",
         "teamVenue":"Comerica Park",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Detroit_Tigers_Logo.jpg",
         "teamDescription":"The Detroit Tigers (14-16) is in the American Central division and are currently on a 6 loss streak with a ranking of 4."
      },
      {  
         "type":"team",
         "teamId":2806,
         "teamFirstName":"Kansas City",
         "teamLastName":"Royals",
         "teamCity":"Kansas City",
         "teamState":"Missouri",
         "teamCountry":"USA",
         "teamVenue":"Kauffman Stadium",
         "teamLogo":"\/mlb\/logos\/team\/MLB_Kansas_City_Royals_Logo.jpg",
         "teamDescription":"The Kansas City Royals (15-15) is in the American Central division and are currently on a 1 loss streak with a ranking of 3."
      }
   ]
}